apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-xfbh
  namespace: e2e-demos-tdnb-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:15c7017637315540240026922765c1b30d684e72f058015375f594beb8b2e84a
        name: my-java-quarkus
        resources: {}
status: {}
